compile:
	 gcc -Wall -ansi -pedantic -std=c99 -Werror -march=native -funroll-all-loops -lcrypto -lssl -O3 bruteforce.c -o bruteforce
	 ./bruteforce 12dada1fff4d4787ade3333147202c3b443e376f
	 ./bruteforce 2c3422d33fb9dd9cde87657408e48f4e635713cb
