#!/usr/bin/env python3
# coding: utf-8

import time

def derp():
  esc = random.element('\x1b','\x9b')

  "\x07",#     BEL beeps;
  "\x08",#     BS  backspaces one column (but not past the beginning of the line);
  "\x09",#     HT  goes to the next tab stop or to the end of the line if there  is no earlier tab stop;
  "\x0a",#     LF  VT  (0x0B, ^^KK) and FF (0x0C, ^^LL) all give a linefeed, and if
  "\x0d",#     CR  gives a carriage return;

  "\x0e",#     SO  activates the G1 character set;
  "\x0f",#     SI  activates the G0 character set;
  "\x18",#     CAN and SUB (0x1A, ^^ZZ) interrupt escape sequences;
  "\x1b",#     ESC starts an escape sequence;
  "\x7f",#     DEL is ignored;
  "\x1b",#     CSI is equivalent to ESC [.

       ESC c     RIS      Reset.
       ESC D     IND      Linefeed.
       ESC E     NEL      Newline.
       ESC H     HTS      Set tab stop at current column.
       ESC M     RI       Reverse linefeed.
       ESC Z     DECID    DEC private identification. The kernel returns the
                          string  ESC [ ? 6 c, claiming that it is a VT102.
       ESC 7     DECSC    Save    current    state    (cursor   coordinates,
                          attributes, character sets pointed at by G0, G1).
       ESC 8     DECRC    Restore state most recently saved by ESC 7.
       ESC [     CSI      Control sequence introducer
       ESC %              Start sequence selecting character set
       ESC % @               Select default (ISO 646 / ISO 8859-1)
       ESC % G               Select UTF-8
       ESC % 8               Select UTF-8 (obsolete)
       ESC # 8   DECALN   DEC screen alignment test - fill screen with E's.
       ESC (              Start sequence defining G0 character set
       ESC ( B               Select default (ISO 8859-1 mapping)
       ESC ( 0               Select VT100 graphics mapping
       ESC ( U               Select null mapping - straight to character ROM
       ESC ( K               Select user mapping - the map that is loaded by
                             the utility mmaappssccrrnn(8).
       ESC )              Start sequence defining G1
                          (followed by one of B, 0, U, K, as above).
       ESC >     DECPNM   Set numeric keypad mode
       ESC =     DECPAM   Set application keypad mode
       ESC ]     OSC      (Should be: Operating  system  command)  ESC  ]  P
                          _n_r_r_g_g_b_b:  set  palette,  with parameter given in 7
                          hexadecimal digits after the final P :-(.  Here  _n
                          is  the  color  (0-15),  and  _r_r_g_g_b_b indicates the
                          red/green/blue values (0-255).   ESC  ]  R:  reset
                          palette


try:
  while True:
    print("%sderp"%(derp()))
    time.sleep()
except KeyboardInterrupt:
  pass
