#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys
from string import ascii_uppercase,ascii_lowercase

ranges = {
  "MATHEMATICAL BOLD" : 0x1d400,
  "MATHEMATICAL ITALIC" : 0x1d434,
  "MATHEMATICAL BOLD ITALIC" : 0x1d468,
  "MATHEMATICAL SCRIPT" : 0x1d49c,
  "MATHEMATICAL BOLD SCRIPT" : 0x1d4d0,
  "MATHEMATICAL FRAKTUR" : 0x1d504,
  "MATHEMATICAL DOUBLE-STRUCK" : 0x1d538,
  "MATHEMATICAL BOLD FRAKTUR" : 0x1d56c,
  "MATHEMATICAL SANS-SERIF" : 0x1d5a0,
  "MATHEMATICAL SANS-SERIF BOLD" : 0x1d5d4,
  "MATHEMATICAL SANS-SERIF ITALIC" : 0x1d608,
  "MATHEMATICAL SANS-SERIF BOLD ITALIC" : 0x1d63c,
  "MATHEMATICAL MONOSPACE" : 0x1d670,
}

capslock = {
  "FULLWIDTH LATIN" : 0xff21,
  "REGIONAL INDICATOR SYMBOL" : 0x1f1e6,
  "PARENTHESIZED LATIN CAPITAL" : 0x1f110,
  "SQUARED LATIN CAPITAL" : 0x1f130,
  "NEGATIVE CIRCLED LATIN CAPITAL" : 0x1f150,
  "NEGATIVE SQUARED LATIN CAPITAL" : 0x1f170,
}

turned = "ɐqɔpǝɟƃɥıɾʞʃɯuodbɹsʇnʌʍxʎz"

def num(i,alphabet):
  try:
    return alphabet.index(i)
  except:
    return -1

def fullwidth(s):
  r = ''
  for letter in s:
    val = ord(letter)
    if val > 0x21 and val < 0x7f:
      r += chr(0xfee0+int(val))
    elif val == 0x20:
      r += chr(0x3000)
    else:
      r += chr(int(val))
  return r

def listit(s,array,alphabet):
  r = ''
  for name in array.keys():
    #r += name.ljust(40)
    r += ''.join([chr(array[name]+num(i,alphabet)) for i in s])
    r += "\n"
  return r

def transcrit(i,alp,reference):
  r = ''
  for letter in i:
    if letter in reference:
      r += alp[reference.index(letter)]
    else:
      r += letter
  return r


if __name__ == "__main__":
  if len(sys.argv) == 1:
    s = sys.stdin.read()
  else:
    s = ' '.join(sys.argv[1:])

  print(fullwidth(s))
  print(transcrit(s.lower(),turned,ascii_lowercase))
  print(listit(s,ranges,ascii_uppercase+ascii_lowercase))
  print(listit(s.upper(),capslock,ascii_uppercase))
