#!/usr/bin/env python2.7
# coding: utf-8

import sys
import binascii

if len(sys.argv) == 2:
  sys.stdout.write(binascii.unhexlify(sys.stdin.read().strip()))
else:
  sys.stdout.write(binascii.hexlify(sys.stdin.read().strip()))
