#!/usr/bin/python3
# coding: utf-8

def safe(c): return '.' if c % 0x80 < 0x20 or c==0x7f else chr(c)

def table_ascii():
  return ''.join([
    ' {}\n'.format(''.join(['{:2x}'.format(i) for i in range(16)])),
    '\n'.join(['{:x} {}'.format(line,' '.join([safe(16*line+i) for i in range(16)])) for line in range(16)])
  ])

def table_color():return '\n'.join([' '.join(['\x1b[3{fg:d};4{bg:d}m{fg:d}{bg:d}\x1b[0m '.format(fg=fg,bg=bg) for fg in range(10)]) for bg in range(10)])

def mergeblocks(a,b):
  a = a.splitlines()
  b = b.splitlines()
  while len(a) > len(b): b.append('')
  return '\n'.join([' '.join([a[i],b[i]]) for i in range(len(b))])

print(mergeblocks(table_ascii(), table_color()))
