#!/usr/bin/env python3
# print occurences of characters in stdin, ordered by codepoint.
import sys
import unicodedata
def name(char):
  try:
    return unicodedata.name(char)
  except:
    return 'MISSINGNO'

stdin = sys.stdin.read()
z = dict([[ord(char),stdin.count(char)] for char in stdin])
keys=[x for x in z.keys()]
keys.sort()
print("\n".join([
  "{:3d} {:6x} {:1s} {} {}".format(
    z[K],
    K,
    "".join([
        "{:02x}".format(i) for i in bytes(chr(K),"utf8")
      ]),
    name(chr(K)),
    chr(K),
    ) for K in keys]))
